baseDir: "/home/stanlew/Documents/ProgressNerfModels/semiSynIn/voxelNerf_clampBottomClamp_fast/"
load_from_epoch: -1
batch_size: 2
num_workers: 1
train_epochs: 50
testPeriod: 10
save_period: 10
device: "cuda:0"
build_weighting_cloud: True

train_dataloader:
    dataloader: "toolsPartsDataloader"
    toolsPartsDataloader: { baseDataDir: "/home/stanlew/data/PNERF-tool-parts/tool_parts/", scenes: ['00','01','02', '03','05'], datasetType: "train", samplesLimit: -1, rel_tools: ['clamp_bottom_clamp']}
test_dataloader:
    dataloader: "toolsPartsDataloader"
    toolsPartsDataloader: { baseDataDir: "/home/stanlew/data/PNERF-tool-parts/tool_parts/", scenes: ['00','01','02', '03','05'], datasetType: "test", samplesLimit: 3, rel_tools: ['clamp_bottom_clamp']}

desired_tool: "clamp_bottom_clamp"
apply_masks: ['clamp_bottom_clamp']
eval_subbatch_size: 1024

raypicker: "weighted_raypicker"
weighted_raypicker: { num_rays: 128}
raysampler: "voxel_grid_bbox"
voxel_grid_bbox: { num_samples: 64}

camera_fx: 536.5441342081624
camera_fy: 537.6663041098749
camera_tx: 324.1496087846382
camera_ty: 224.2990274169881
render_resoluion: [640,480]
coarse_model:
    nnModel: "fast_nerf"
    fast_nerf: {includeOrigPos: True, pos_enc_levels: 10, dir_enc_levels: 4, hidden_units_pos: 384, hidden_units_dir: 128, layers_pos: 8, layers_dir: 4, D: 8, skips: [4]}
posEncoder: {encoder: "positional_encoder", positional_encoder: {levels: 10, includeOrig: True}}
dirEncoder: {encoder: "positional_encoder", positional_encoder: {levels: 4}}
optim_lr: 0.001

init_voxel_size: 0.01
voxel_visit_after_epoch: 50
voxel_visit_depth_stoppage: 0.01
voxel_visit_factor: 0.99
half_voxels_schedule: []
prune_voxels_schedule: []
prune_voxels_sample_count: 16000
prune_voxels_gamma: 0.5

make_cache: True
cache_l: 1024
cache_voxel_size: 0.001
cache_D: 8

boundary_min_maxes: [-0.065,  -0.03, -0.025, 0.045,  0.1,  0.025]

renderer: "voxel_neural_renderer"
voxel_neural_renderer: {}
train_loss:
    loss_fn: "mse_loss"
    mse_loss: {}
test_loss:
    loss_fn: "mse_loss"
    mse_loss: {}