baseDir: "/home/stanlew/Documents/ProgressNerfModels/ycb_object/soup_can/"
load_from_epoch: -1
batch_size: 1
num_workers: 1
train_epochs: 200
testPeriod: 10
save_period: 10
device: "cuda:0"
build_weighting_cloud: True

train_dataloader:
    dataloader: "YCBObjectDataloader"
    YCBObjectDataloader: { baseDataDir: "/home/stanlew/data/ycb/ycb", object_label: "005_tomato_soup_can", samplesLimit: 25} 
test_dataloader:
    dataloader: "YCBObjectDataloader"
    YCBObjectDataloader: { baseDataDir: "/home/stanlew/data/ycb/ycb", object_label: "005_tomato_soup_can", samplesLimit: 5} 

desired_tool: "005_tomato_soup_can"
apply_masks: ['005_tomato_soup_can']
eval_subbatch_size: 1024

raypicker: "weighted_raypicker"
weighted_raypicker: { num_rays: 1024}
raysampler: "voxel_grid_bbox"
voxel_grid_bbox: { num_samples: 64}

camera_fx: 3597.4731624786377
camera_fy: 3597.4724747318223
camera_tx: 2132.6012997593516
camera_ty: 1395.4193524717593
render_resoluion: [4272,2848]
coarse_model:
    nnModel: "fast_nerf"
    fast_nerf: {includeOrigPos: True, pos_enc_levels: 15, dir_enc_levels: 4, hidden_units_pos: 384, hidden_units_dir: 128, layers_pos: 8, layers_dir: 4, D: 8, use_view_dirs: False}
posEncoder: {encoder: "positional_encoder", positional_encoder: {levels: 15, includeOrig: True}}
dirEncoder: {encoder: "positional_encoder", positional_encoder: {levels: 4}}
optim_lr: 0.001

init_voxel_size: 0.01
voxel_visit_after_epoch: 50
voxel_visit_depth_stoppage: 0.01
voxel_visit_factor: 0.99
half_voxels_schedule: []
prune_voxels_schedule: []
prune_voxels_sample_count: 16000
prune_voxels_gamma: 0.5

make_cache: True
cache_l: 1024
cache_voxel_size: 0.001
cache_D: 8

boundary_min_maxes: [-0.05, -0.05, -0.05, 0.05, 0.05, 0.05]

renderer: "voxel_neural_renderer"
voxel_neural_renderer: {}
train_loss:
    loss_fn: "mse_loss"
    mse_loss: {}
test_loss:
    loss_fn: "mse_loss"
    mse_loss: {}