baseDir: "/home/stanlew/Documents/ProgressNerfModels/OGNerf_sigmoid/"
load_from_epoch: -1
device: "cuda:0"
raypicker: "random_raypicker"
random_raypicker: { num_rays: 1024}
eval_subbatch_size: 256
raysampler: "perturbed_raysampler"
perturbed_raysampler: { near_plane: 0.5, far_plane: 4.0, num_samples: 100, sample_std: 0.1}
camera_fx: 536.5441342081624
camera_fy: 537.6663041098749
camera_tx: 324.1496087846382
camera_ty: 224.2990274169881
render_resoluion: [640,480]
coarse_model:
    nnModel: "OGNerf"
    OGNerf: {pos_enc_levels: 10, dir_enc_levels: 4, hidden_dims: 128}
fine_model:
    nnModel: "OGNerf"
    OGNerf: {pos_enc_levels: 10, dir_enc_levels: 4, hidden_dims: 128}
    raysampler: "weighted_raysampler"
    weighted_raysampler: {num_samples: 100}
posEncoder: {encoder: "positional_encoder", positional_encoder: {levels: 10}}
dirEncoder: {encoder: "positional_encoder", positional_encoder: {levels: 4}}
renderer: "neural_renderer"
neural_renderer: {}